# Generated by Django 4.0 on 2022-01-04 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=150)),
                ('icon', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=150)),
                ('icon', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=150)),
                ('icon', models.BinaryField(blank=True)),
                ('avalible_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.gameclass')),
            ],
        ),
    ]
