# Generated by Django 4.0 on 2022-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameclass',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
