# Generated by Django 4.0 on 2022-01-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_abilities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilities',
            name='basekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.baseclass'),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='classkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.gameclass'),
        ),
        migrations.AlterField(
            model_name='discclassracerelationship',
            name='basekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.baseclass'),
        ),
        migrations.AlterField(
            model_name='discclassracerelationship',
            name='classkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.gameclass'),
        ),
        migrations.AlterField(
            model_name='discclassracerelationship',
            name='racekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.race'),
        ),
        migrations.AlterField(
            model_name='stance',
            name='basekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.baseclass'),
        ),
        migrations.AlterField(
            model_name='stance',
            name='classkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.gameclass'),
        ),
        migrations.AlterField(
            model_name='weaponpowerclassrelationship',
            name='basekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.baseclass'),
        ),
        migrations.AlterField(
            model_name='weaponpowerclassrelationship',
            name='classkey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.gameclass'),
        ),
    ]
