# Generated by Django 4.0 on 2022-01-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_remove_baseclass_avalible_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilities',
            name='cast_time',
            field=models.FloatField(),
        ),
    ]
