# Generated by Django 4.0 on 2022-01-05 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_alter_abilities_cast_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilities',
            name='racekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.race'),
        ),
        migrations.AlterField(
            model_name='skillclassrelationship',
            name='bonus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skillclassrelationship',
            name='resrictions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
