# Generated by Django 4.0 on 2022-01-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0009_abilities_racekey_alter_skillclassrelationship_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='gameclass',
            name='races',
            field=models.ManyToManyField(to='wiki.RaceTest'),
        ),
    ]
