# Generated by Django 4.0 on 2022-01-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_racetest_gameclass_races'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameclass',
            name='races',
        ),
        migrations.DeleteModel(
            name='RaceTest',
        ),
    ]
