# Generated by Django 4.0 on 2022-01-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_remove_gameclass_races_delete_racetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilities',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='weaponpower',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
