# Generated by Django 4.0 on 2022-01-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_abilities_icon_weaponpower_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilities',
            name='disckey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.discipline'),
        ),
    ]
