# Generated by Django 4.0 on 2022-01-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_alter_discipline_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclass',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gameclass',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stance',
            name='effects',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='abilities',
            name='description',
            field=models.TextField(default=None, max_length=1500),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='dropper',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='effects',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='items',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='trainer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skillclassrelationship',
            name='bonus',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='skillclassrelationship',
            name='resrictions',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
