# Generated by Django 4.0 on 2022-01-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_baseclass_description_discipline_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='con_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='con_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='dex_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='dex_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='effects',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='int_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='int_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='spi_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='spi_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='str_b',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='str_m',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
