# Generated by Django 4.0 on 2022-01-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0017_race_con_b_race_con_m_race_cost_race_dex_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseclass',
            name='effects',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
